name: Release Charts on OCI

on:
  push:
    tags:
      - "centrifugo-*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch history
        run: git fetch --prune --unshallow
